### ISSUE TITLE
releaes

### ISSUE THREAD

**Issue by ahmed-tasaly** [abdenassar01/muslim#1]
Assalam alaykom

Is there any releases ?

**Comment by abdenassar01** [comment]
Hello sir,

There is a release and I will upload it tomorrow.

Thank you for your asking.

**Comment by abdenassar01** [comment]
The first version of the app is released so you can try it right now.

I will appreciate it if you could leave me a feedback after trying the app and may be suggest the changes you'd like to be added in the next version 😇.

**Comment by ahmed-tasaly** [comment]
@abdenassar01 

### Some notes 
These notes are examples

![Screenshot_2022-10-13-20-26-31-380-edit_com muslim](https://user-images.githubusercontent.com/64969309/195677231-091ed6f7-7971-4347-99c7-4c6e7a2b8608.jpg)
![Screenshot_2022-10-13-20-26-12-989-edit_com muslim](https://user-images.githubusercontent.com/64969309/195677240-587a02a5-25ca-423d-b252-be0957a8a1e8.jpg)
![Screenshot_2022-10-13-20-26-04-537-edit_com muslim](https://user-images.githubusercontent.com/64969309/195677257-8622a691-8f09-47af-9d4f-4aa815ee6bfe.jpg)

Some Other Notes ---→
I think you should :
- Use a **bigger font size** or add an option to increase the font size for the **main menu** and for **azkar** and **quran**

- Use **paged mode** and **page numbers**

-  add **horizontal navigation** through quran 

- add **auto azkar** option similar to auto azkar app in playstore

- add **counter** for azkar that counts down for each zeker 

- add posititions of **quraters** and **ahzab** 

- add **audio** recetation of quran

- add multiple readings of quran **(القراءات)**

**Comment by abdenassar01** [comment]
Thank you @ahmed-tasaly  for your feedback.

I confirm you that your notes are taken and we will be working on them in the next release inshallah.

I appreciate your collaboration. 

author: @abdenassar01
